### ISSUE TITLE
AutohotkeyCE Source Code

### ISSUE THREAD

**Issue by azhkprtw** [Micha-ohne-el/struct#1]
#https://github.com/ahkscript/AutoHotkeyCE/issues/3

In this thread, I had inquired about AutoHotKeyCE source code. I was wondering if it was available somewhere. I was looking to try to compile the code for other architectures

**Comment by SimplyMika** [comment]
Hi there!

I believe you've cought yourself the wrong Micha 😅
I've never heard of AutoHotkeyCE and certainly don't have its source code.

That said, I also can't think of another Micha in the AHK community. You could try creating a forum post about it or asking on the AHK Discord server. Maybe someone else knows more than I do.

Feel free to mention me once you've found what you're looking for :)

Good luck!
